apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeoulyeorm
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yeoulyeorm
  template:
    metadata:
      labels:
        app: yeoulyeorm
    spec:
      containers:
        - name: yeoulyeorm
          image: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yeoulyeorm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80